name: PR:5.x

on:
  pull_request:
    branches:
      - 5.x

jobs:
  Linux:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-Linux.yaml@add-custom-action
    with:
      workflow_branch: 'add-custom-action'

